### ISSUE TITLE
Update localization support

### ISSUE THREAD

**Issue by Adaptivity** [Glassmaker/ExtraTiC-Localization#11]
Localization support was improved a lot in latest Tinkers Construct. So, you should add it in ExtraTiC too. See more: https://github.com/Qowyn/TinkersConstruct/commit/7ae5a92a8f30fba3c11dc391ff03b6c38b226444

**Comment by Adaptivity** [comment]
Just to clarify, @Glassmaker will you implement it in the next version? Just want to make sure what you know about it.

**Comment by Glassmaker** [comment]
Mhm, it will be implemented for the Tinkers' 1.8.x update :)
