### ISSUE TITLE
Draconium Tools

### ISSUE THREAD

**Issue by Voxel-Friend** [Glassmaker/ExtraTiC-Localization#26]
1. First of all, Hey Glassy and Company!  o/

2. Been having problems trying to make the Draconium tools added by ExTiC, to no avail.
    I've tried it with the part builder and casting table both. Neither work.
    I've tried a clean instance with the following mods installed using the Curse Launcher:
    -forge-10.13.4.1448
    -CodeChickenCore-1.7.10-1.0.6.43-universal.jar
    -CoFHCore-[1.7.10]3.0.2-262.jar
    -CoFHLib[1.7.10]1.0.2-160.jar
    -Draconic-Evolution-1.7.10-1.0.1c.jar
    -ExtraTiC-1.7.10-1.4.5.jar
    -Mantle-1.7.10-0.3.2.jar
    -NotEnoughItems-1.7.10-1.0.4.107-universal.jar
    -TConstruct-1.7.10-1.8.5.jar

3. Super hyped about that RF Smeltery, any news about that?

**Comment by Voxel-Friend** [comment]
For the record, I should also note that I was having the same issue with both the vanilla launcher, as well as AT Launcher, using the same versions of afore mentioned mods. Not that I think it matters but just presenting all the facts.

**Comment by Voxel-Friend** [comment]
Confirmed to still be an issue with latest Draconic Evolution.

**Comment by Voxel-Friend** [comment]
Sigh... Didn't even cross my mind to try other items. I realize now that I had to use Wyvern/Awakened Cores in the part builder. Sorry for the trouble.

P.S. Is there anyway you might be able to add some sort of note on your mod pages to clarify this, and other unorthodox materials, so that other people do not make the same mistake?

**Comment by Shahelion** [comment]
Calling them Wyvern or Awakened Draconic parts would be a good step. Calling them Draconium parts implies using the ingots.
